config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  root "books#index"
  resources :books
  
  root "authors#index"
  resources :authors

  resources :products do
    collection {post :import }
  end 
  root to: "products#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
has_many :books
validates :name, presence: true
validates :name, uniqueness: true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :author
	validates  :name, presence: true

end

app/models/create_book.rb
class CreateBook < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

	def index
		@authors =  Author.all
		@count = Book.group("author_id").count
	end

	def new
		@author = Author.new
	end

	def create
		@author = Author.new(author_params)

		if @author.save
			redirect_to authors_path

		else

            puts "============================================ /n #{@author.errors.messages} /n ======================================================="
			redirect_to new
		end
	end

	def show
		@author = Author.find(params[:id])
		@books = @author.books
	end
	
	def edit
		@author = Author.find(params[:id])
	end

	def update
		@author = Author.find(params[:id])
		@author.update(author_params)
		redirect_to authors_path
	end
    
	def destroy
		@author = Author.find(params[:id])
		@author.destroy 
		redirect_to authors_path, :notice =>"author record deleted"
	end



	private
	def author_params
		params.require(:author).permit(:name)
	end

end

app/controllers/book_controller.rb
class BookController < ApplicationController
	def index
		@book = Book.all
	end

	def new
		@book = Book.new
	end

	def create
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
	end

	def update
	end

	def destroy
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	
	before_action :authenticate_user!, except: [:index]

	def index
		@books = Book.all
	end

	def new
		@book = Book.new
	end

	def create

		if params[:author_id].nil?
			author = Author.create(name: params[:book][:writer_name]) 
			
			new_book_params = book_params.merge(author_id: author.id)

		end


		@book = Book.new(new_book_params)
		if @book.save
			redirect_to books_path
		else
			redirect_to new
		end
	end

	def show
		@book = Book.find(params[:id])
	end

	def edit
		@book = Book.find(params[:id])
	end

	def update
		@book = Book.find(params[:id])
		@book.update(book_params)
		redirect_to books_path
	end
    
	def destroy
		@book = Book.find(params[:id])
		 @book.destroy 
		redirect_to books_path,  :notice =>"book record deleted"
	end

	private

	def book_params
		params.require(:book).permit(:name, :price, :author_id)
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

def import 
	Product.import(params [:file])
	redirect_to root_url, :notice=> "books imported"
end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :father_name])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
module BookHelper
end

app/views/authors/_form.html.erb
<%= form_for author do |f| %>

		<div class="container"> <!-- for center alin give container -->
    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text forn-control" id="addon-wrapping">author_Name</span>
      <%= f.text_field :name,  class: 'form-control' %>
    </div>
		
		<div class="text-right d-flex justify-content-end ">
			<%= f.submit class: "btn btn-secondary" %>
		</div>
	</div>

<% end %>

app/views/authors/edit.html.erb
<h1 style="color:red">author Edit </h1>
<%= render 'form', author: @author %>
</br >
<div class="container text-right">
	<div class="d-flex justify-content-end">
		<%= link_to "Back", :back , class: 'd-block btn btn-primary' %>
	</div>
</div>

app/views/authors/index.html.erb
<style>
table, th, td {
  border: 1px solid black; }
</style>
<br>

<table class="table table-striped  table-hover ">
	  <caption>List of author</caption>
  <thead>
    <tr class="bg-danger">
      <th>id</th>
      <th>Author_name</th>
      <th>Total_Books_of_author</th>
      <th>Books_of_author</th>

      <% if current_user %>
      <th>Show</th> 
      <th>edit</th>
      <th>destroy</th>
      <% end%>
  </thead>
	<tbody>		
			<% @authors.each do |author|%>
		<tr >	
			<th ><%= author.id %></th>
			<td ><%= author.name  %></td>
			<td ><%= @count[author.id] %> </td>
			<td ><%= author.books.map {|obj| obj.name} %> </td>
			<% if current_user %> <!-- ager koi user present ha to tb ya show ker vay other vise nahi -->
			<td ><%= link_to "Show" , author_path(author.id), class: "btn btn-secondary"%></td>
			<td ><%= link_to "edit", edit_author_path(author.id), class: "btn btn-primary" %></td>
			<td ><%= link_to "destroy", author_path(author.id), class: "btn btn-danger ",  data: {:confirm => "Arue you sure?"}, :method => :delete %></td>
			<% end %>
		</tr>
			<% end%>
	</tbody>
</table>

app/views/authors/new.html.erb
<h1 style="color:#ff0000 ;text-align: center;" > New Author</h1>
<%= render 'authors/form', author: @author %>
<br /> 
<div class="container text-right">
	<div class="d-flex justify-content-end">
		<%= link_to "Back", :back , class: 'd-block btn btn-primary' %>
	</div>
</div>

app/views/authors/show.html.erb
<form>
<style>
table, th, td {
  border: 1px solid black;}
</style>
<h1 style="color:brown; text-align: center; "> Author record </h1>
<table class="table table-striped  table-hover " >
	<tr class="bg-success" >
		<th> id</th>
		<th> name</th>
		<th> Edit</th>
		<th> Destory</th>
		<tr>
	<tr>
		<td><%= @author.id %></td>
		<td><%= @author.name %></td>
		<td ><%= link_to "Edit", edit_author_path(@author.id), class: "btn btn-primary" %></td>
		<td ><%= link_to "Destroy", edit_author_path(@author.id), class: "btn btn-danger" %></td>

	<tr>
</table>	
</form>
<br/>
<h1 style="color:brown; text-align: center;">Author_books</h1>
<%= render 'books/index', book: @books %>
<%= link_to 'Back', :back ,class: "btn btn-primary"%>

app/views/book/index.html.erb
<%= link_to "Create New Book" , new_book_path %>
<% @book.each do |b|%>
<li style="color:green">
<tr>	
	<td ><%= b.name %></td>
	<td><%= b.writer_name %></td>
	<td><%= b.price %></td>
	<li><%= link_to "Show", book_path(b.id)%></li>
	<li><%= link_to "edit", edit_book_path(b.id)%></li>
	<li><%= link_to "destroy", book_path(b.id), data: {:confirm => "Arue you sure?"}, :method => :delete %></li>
<tr>
</li>
<hr/>
<% end%>

app/views/book/show.html.erb
<h1 style="color:brown;"> Book record </h1>
<tr>
	<td><%= @book.name %></td>
	<td><%= @book.writer_name %></td>
	<td><%= @book.price %></td>
</tr>

app/views/books/_form.html.erb
<%= form_for book do |book| %>

	<div class="container"> <!-- for center alin give container -->
		<div class="input-group flex-nowrap mb-3">
	  	<span class="input-group-text forn-control" id="addon-wrapping">Book_Name</span>
	  	<%= book.text_field :name, class: 'form-control' %>
		</div>

		<div class="input-group flex-nowrap mb-3" >
	  	<span class="input-group-text forn-control" id="addon-wrapping">price</span>
	  	<%= book.number_field :price, class: 'form-control' %>
		</div>

    <div class="input-group flex-nowrap mb-3">
      <span class="input-group-text forn-control" id="addon-wrapping">Author_Name</span>
      <%= book.text_field :writer_name,  class: 'form-control' %>
    <%= book.collection_select :author_id, Author.order(:name),:id,:name, include_blank: true, class: 'form-control'%>


    </div>
		
		<div class="text-right d-flex justify-content-end">
			<%= book.submit class: "btn btn-secondary" %>
		</div>
	</div>

<% end %>

app/views/books/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Books</a>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="http://localhost:3000/">Home</a>
        </li>
        
        <li class="nav-item ">
          <%= link_to "All Authors List " , authors_path, class: 'nav-link ' %>
        </li>
        

        <% if current_user %>
        <li class="nav-item ">
          <%= link_to "Create New Book" , new_book_path, class: 'nav-link ' %>
        </li>
        <%end%>

        <% if current_user %>
        <li class="nav-item ">
          <%= link_to "Create a Author" , new_author_path, class: 'nav-link ' %>
        </li>
        <%end%>  
      </ul>
      
      <% unless current_user %>
     
      <div class="d-flex">
        <%= link_to 'sign up', new_user_registration_path, class: "btn btn-outline-success" %>
      </div>
     
      <div class="d-flex">
        <%= link_to 'sign in', new_user_session_path, class: "btn btn-outline-success" %>
      </div>

       <% else %>
      <div class="d-flex">
        <%= link_to 'sign out', destroy_user_session_path, method: :delete, class: "btn btn-outline-success" %>
      </div>
      <% end %>

    </div>
  </div>
</nav>

app/views/books/_index.html.erb
<style>
table, th, td {
  border: 1px solid black; }
</style>
<br>

<table class="table table-striped  table-hover ">
	  <caption>List of Books</caption>

  <thead>
    <tr class="bg-success">
      <th>id</th>
      <th>name</th>
      <th>Author_name</th>
      <th>price</th>
      <% if current_user %>
      <th>Show</th> 
      <th>edit</th>
      <th>destroy</th>
      <% end%>
    </tr>
  </thead>
	<tbody>		
		<% book.each do |book|%>
		<tr >	
			<th ><%= book.id %></th>
			<td ><%= book.name  %></td>
			<td ><%= book.author.name %></td>
			<td ><%= book.price %></td>
			<% if current_user %> <!-- ager koi user present ha to tb ya show ker vay other vise nahi -->
			<td ><%= link_to "Show" , book_path(book.id), class: "btn btn-secondary"%></td>
			<td ><%= link_to "edit", edit_book_path(book.id), class: "btn btn-primary" %></td>
			<td ><%= link_to "destroy", book_path(book.id), class: "btn btn-danger ",  data: {:confirm => "Arue you sure?"}, :method => :delete %></td>
			<% end %>
		</tr>

<% end%>
	</tbody>
</table>

app/views/books/edit.html.erb
<h1 style="color:red">Book Edit </h1>
<%= render 'form', book: @book %>
</br >
<div class="container text-right">
	<div class="d-flex justify-content-end">
		<%= link_to "Back", :back , class: 'd-block btn btn-primary' %>
	</div>
</div>

app/views/books/index.html.erb
<%= render 'books/index', book: @books %>

app/views/books/mybook.html.erb
<h1>hello books</h1>

app/views/books/new.html.erb
<h1 style="color:#ff0000"> New Book</h1>
<%= render 'books/form', book: @book %>
<br /> 
<div class="container text-right">
	<div class="d-flex justify-content-end">
		<%= link_to "Back", :back , class: 'd-block btn btn-primary' %>
	</div>
</div>

app/views/books/show.html.erb
<form>
<style>
table, th, td {
  border: 1px solid black;}
</style>
<h1 style="color:brown; text-align: center;"> Book record </h1>
<table class="table table-striped  table-hover ">
	<tr  class="bg-success" >
		<th> id</th>
		<th> name</th>
		<th> author_name </th>
		<th> price </th>
	</tr>
	<tr>
		<td><%= @book.id %></td>
		<td><%= @book.name %></td>
		<td><%= @book.author.name %></td>
		<td><%= @book.price %></td>
	</tr>

</table>	
</form>
<%= link_to 'Back', :back ,class: "btn btn-primary"%>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head style="color: red">
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>BookProject</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body> 
    <%= render 'books/header'  %>
    <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/products/index.html.erb
<h12> importing books</h12>
<%= form_tag import_products_path, multipart: true do %>
<%= file_field_tag :file %>
<%= submit_tag "import" %>
<% end %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "sign in", new_session_path(resource_name) %><br />
<% end %>
<br >
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_user_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>